@BudgetFlow.Api_HostAddress = http://localhost:8080

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "Email": "somehelp@gmail.com",
  "FullName": "Jora Pop",
  "Password": "7878"
}

###


### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "Email": "somehelp@gmail.com",
  "Password": "7878"
}

###


### Refresh
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "UXcZzXiy2VM5R7WO1kYMG4dH7XDdMmHS5kLEYZj537SxGKxP6mrvp/osz+OtgPFtXwMyZLaV3teZ2ebCd5QD0Q=="
}
###

GET http://localhost:8080/api/test/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YmQyOTNkOS05NWRjLTQ1OGYtYjdlZi02NjdjMGJmNzBhYjQiLCJlbWFpbCI6InNvbWVoZWxwQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiOWJkMjkzZDktOTVkYy00NThmLWI3ZWYtNjY3YzBiZjcwYWI0IiwiZXhwIjoxNzczNjA2NDE2LCJpc3MiOiJCdWRnZXRGbG93IiwiYXVkIjoiQnVkZ2V0Rmxvdy5DbGllbnQifQ.hh9LrYi8ANpHb9oeBw5tz6h2G8iShbHm2sR6E69neWU

###