@host = http://localhost:8080
@accessToken = paste-access-token
@refreshToken = paste-refresh-token

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "Email": "somehelp22@gmail.com",
  "FullName": "Jora Pop",
  "Password": "7878"
}

###


### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "Email": "somehelp22@gmail.com",
  "Password": "7878"
}

###


### Refresh
POST {{host}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
###

### test me
GET {{host}}/api/test/me
Accept: application/json
Authorization: Bearer {{accessToken}}

###

### Create wallet
POST {{host}}/api/wallets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Main wallet",
  "currency": "USD",
  "initialBalance": 100.00
}

###

### List own wallets
GET {{host}}/api/wallets
Accept: application/json
Authorization: Bearer {{accessToken}}

###
